# Generated by Django 5.0.3 on 2024-03-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivehandler', '0003_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
