# Generated by Django 5.0.3 on 2024-03-20 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivehandler', '0004_rename_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.CharField(default=django.utils.timezone.now, max_length=2500),
            preserve_default=False,
        ),
    ]
